# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Abhinand
tagline:          'Personal blog'
description:      'My ramblings, random thoughts and the occasional complaint.'
url:              http://abhinandh.com
baseurl:          /

author:
  name:           'Abhinand'
  url:            http://abhinandh.com

paginate:         10

# custom vars
github:
  repo: https://github.com/abnd90
